// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: game.proto

// 生成的 Go 代码所在的包名

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义统一的消息包（替代之前的 GameMessage JSON）
type GameMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Type    string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                    // 消息类型: chat, move, init, leave, match_req, match_success
	UserId  uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 玩家 ID
	Content string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`              // 聊天内容
	X       float32                `protobuf:"fixed32,4,opt,name=x,proto3" json:"x,omitempty"`                        // 坐标 X
	Y       float32                `protobuf:"fixed32,5,opt,name=y,proto3" json:"y,omitempty"`                        // 坐标 Y
	Z       float32                `protobuf:"fixed32,6,opt,name=z,proto3" json:"z,omitempty"`                        // 坐标 Z
	// 列表类型：用于同步历史记录或玩家列表
	Players []*PlayerPos `protobuf:"bytes,7,rep,name=players,proto3" json:"players,omitempty"`
	History []*ChatLog   `protobuf:"bytes,8,rep,name=history,proto3" json:"history,omitempty"`
	// 修改内容：新增基于强类型的房间ID字段
	// 修改原因：支持基于房间的物理隔离广播与对局，大厅聊天与房间隔离
	RoomId string `protobuf:"bytes,9,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// ===== 新增代码 START =====
	// 修改内容：新增朝向同步字段 rot_y，用于远端玩家丝滑旋转同步与多帧视觉稳定
	// 修改原因：在 move 类消息中附带 transform.eulerAngles.y，避免远端旋转出现轻微卡顿
	// 影响范围：仅影响 move/同步类消息；大厅未必填充该字段
	RotY float32 `protobuf:"fixed32,10,opt,name=rot_y,json=rotY,proto3" json:"rot_y,omitempty"`
	// 修改内容：新增客户端输入同步字段（服务端权威接管所需）
	// 修改原因：将客户端输入上行给服务端，由服务端统一推进状态与广播快照
	// 影响范围：battle 场景输入消息；其他消息类型可保持默认零值
	InputX        float32 `protobuf:"fixed32,11,opt,name=input_x,json=inputX,proto3" json:"input_x,omitempty"`
	InputY        float32 `protobuf:"fixed32,12,opt,name=input_y,json=inputY,proto3" json:"input_y,omitempty"`
	IsCharging    bool    `protobuf:"varint,13,opt,name=is_charging,json=isCharging,proto3" json:"is_charging,omitempty"`
	IsAttacking   bool    `protobuf:"varint,14,opt,name=is_attacking,json=isAttacking,proto3" json:"is_attacking,omitempty"`
	MouseX        float32 `protobuf:"fixed32,15,opt,name=mouse_x,json=mouseX,proto3" json:"mouse_x,omitempty"`
	MouseY        float32 `protobuf:"fixed32,16,opt,name=mouse_y,json=mouseY,proto3" json:"mouse_y,omitempty"` // ===== 新增代码 END =====
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GameMessage) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GameMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GameMessage) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *GameMessage) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *GameMessage) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *GameMessage) GetPlayers() []*PlayerPos {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameMessage) GetHistory() []*ChatLog {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *GameMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameMessage) GetRotY() float32 {
	if x != nil {
		return x.RotY
	}
	return 0
}

func (x *GameMessage) GetInputX() float32 {
	if x != nil {
		return x.InputX
	}
	return 0
}

func (x *GameMessage) GetInputY() float32 {
	if x != nil {
		return x.InputY
	}
	return 0
}

func (x *GameMessage) GetIsCharging() bool {
	if x != nil {
		return x.IsCharging
	}
	return false
}

func (x *GameMessage) GetIsAttacking() bool {
	if x != nil {
		return x.IsAttacking
	}
	return false
}

func (x *GameMessage) GetMouseX() float32 {
	if x != nil {
		return x.MouseX
	}
	return 0
}

func (x *GameMessage) GetMouseY() float32 {
	if x != nil {
		return x.MouseY
	}
	return 0
}

type PlayerPos struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	X      float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y      float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z      float32                `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	RotY   float32                `protobuf:"fixed32,5,opt,name=rot_y,json=rotY,proto3" json:"rot_y,omitempty"`
	// 修改内容：新增服务端状态快照字段
	// 修改原因：服务端需要将玩家状态机状态、生命值、能量值下行给客户端
	// 影响范围：state 类型广播与战斗 HUD 同步
	CurrentState  uint32 `protobuf:"varint,6,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	Hp            int32  `protobuf:"varint,7,opt,name=hp,proto3" json:"hp,omitempty"`
	Energy        int32  `protobuf:"varint,8,opt,name=energy,proto3" json:"energy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerPos) Reset() {
	*x = PlayerPos{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerPos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPos) ProtoMessage() {}

func (x *PlayerPos) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPos.ProtoReflect.Descriptor instead.
func (*PlayerPos) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerPos) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PlayerPos) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerPos) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerPos) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerPos) GetRotY() float32 {
	if x != nil {
		return x.RotY
	}
	return 0
}

func (x *PlayerPos) GetCurrentState() uint32 {
	if x != nil {
		return x.CurrentState
	}
	return 0
}

func (x *PlayerPos) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *PlayerPos) GetEnergy() int32 {
	if x != nil {
		return x.Energy
	}
	return 0
}

type ChatLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatLog) Reset() {
	*x = ChatLog{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatLog) ProtoMessage() {}

func (x *ChatLog) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatLog.ProtoReflect.Descriptor instead.
func (*ChatLog) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *ChatLog) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatLog) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x05proto\"\xaa\x03\n" +
	"\vGameMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\f\n" +
	"\x01x\x18\x04 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x06 \x01(\x02R\x01z\x12*\n" +
	"\aplayers\x18\a \x03(\v2\x10.proto.PlayerPosR\aplayers\x12(\n" +
	"\ahistory\x18\b \x03(\v2\x0e.proto.ChatLogR\ahistory\x12\x17\n" +
	"\aroom_id\x18\t \x01(\tR\x06roomId\x12\x13\n" +
	"\x05rot_y\x18\n" +
	" \x01(\x02R\x04rotY\x12\x17\n" +
	"\ainput_x\x18\v \x01(\x02R\x06inputX\x12\x17\n" +
	"\ainput_y\x18\f \x01(\x02R\x06inputY\x12\x1f\n" +
	"\vis_charging\x18\r \x01(\bR\n" +
	"isCharging\x12!\n" +
	"\fis_attacking\x18\x0e \x01(\bR\visAttacking\x12\x17\n" +
	"\amouse_x\x18\x0f \x01(\x02R\x06mouseX\x12\x17\n" +
	"\amouse_y\x18\x10 \x01(\x02R\x06mouseY\"\xb0\x01\n" +
	"\tPlayerPos\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x02R\x01z\x12\x13\n" +
	"\x05rot_y\x18\x05 \x01(\x02R\x04rotY\x12#\n" +
	"\rcurrent_state\x18\x06 \x01(\rR\fcurrentState\x12\x0e\n" +
	"\x02hp\x18\a \x01(\x05R\x02hp\x12\x16\n" +
	"\x06energy\x18\b \x01(\x05R\x06energy\";\n" +
	"\aChatLog\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontentB\tZ\a./protob\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_game_proto_goTypes = []any{
	(*GameMessage)(nil), // 0: proto.GameMessage
	(*PlayerPos)(nil),   // 1: proto.PlayerPos
	(*ChatLog)(nil),     // 2: proto.ChatLog
}
var file_game_proto_depIdxs = []int32{
	1, // 0: proto.GameMessage.players:type_name -> proto.PlayerPos
	2, // 1: proto.GameMessage.history:type_name -> proto.ChatLog
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
