// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gameplay.sql

package sqlc

import (
	"context"
)

const getPlayerPosition = `-- name: GetPlayerPosition :one
SELECT payload
FROM player_positions
WHERE user_id = $1
`

func (q *Queries) GetPlayerPosition(ctx context.Context, userID int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPlayerPosition, userID)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}

const insertMessage = `-- name: InsertMessage :exec

INSERT INTO messages (sender, content)
VALUES ($1, $2)
`

type InsertMessageParams struct {
	Sender  string
	Content string
}

// 网关侧(gameplay 域):聊天记录 + 玩家位置存档(JSONB)
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage, arg.Sender, arg.Content)
	return err
}

const upsertPlayerPosition = `-- name: UpsertPlayerPosition :exec
INSERT INTO player_positions (user_id, payload)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET payload = EXCLUDED.payload,
    updated_at = now()
`

type UpsertPlayerPositionParams struct {
	UserID  int64
	Payload []byte
}

func (q *Queries) UpsertPlayerPosition(ctx context.Context, arg UpsertPlayerPositionParams) error {
	_, err := q.db.Exec(ctx, upsertPlayerPosition, arg.UserID, arg.Payload)
	return err
}
