// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Message struct {
	ID        int64
	CreatedAt time.Time
	Sender    string
	Content   string
}

type PlayerPosition struct {
	UserID    int64
	Payload   []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt **time.Time
	Username  string
	Password  string
	Email     string
}
